project_id = "siefyekwetkywwgaqqhv"

[functions.send-notification-email]
verify_jwt = false

[functions.admin-ai-chat]
verify_jwt = false

[functions.admin-create-bucket]
verify_jwt = false

[functions.admin-seed-docs]
verify_jwt = false
